version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cb_lab_db
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U DB_USER -d DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cb_lab_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cb_lab_backend
    environment:
      DATABASE_USER: DB_USER
      DATABASE_PASSWORD: DB_PASSWORD
      DATABASE_NAME: DB_NAME
      DATABASE_HOST: DB_HOST
      SECRET_KEY: SECRET_KEY
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ## Definições de superusuário para criação automática
      # SUPERUSER_NAME: SU_NAME  # Default: Admin
      # SUPERUSER_EMAIL: SU_EMAIL  # Default: admin@cb-lab.com
      # SUPERUSER_PWD: SU_PASSWORD  # Default: admin123 
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8000
    networks:
      - cb_lab_network

volumes:
  postgres_data:
    driver: local

networks:
  cb_lab_network:
    driver: bridge
